-- WG1 - Pivot payments, stage 2: Jinja + SQL.
-- Same result as stage 1, but the per-method CASE expressions are generated by a
-- Jinja for-loop over a list of payment methods, so adding a method becomes a
-- one-line change instead of a new hand-written CASE.

{%- set payment_methods = ['bank_transfer', 'coupon', 'credit_card', 'gift_card'] -%}

with payments as (

    select * from {{ ref('stg_jaffle_shop__payments') }}

)

select
    order_id,

    {% for payment_method in payment_methods -%}
    sum(case when payment_method = '{{ payment_method }}' then amount else 0 end) as {{ payment_method }}_amount,
    {% endfor -%}

    sum(amount) as total_amount

from payments

group by order_id
