jaffle_shop:
  outputs:
    dev:
      dataset: dbt_lushep
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: sql-training-422508
      threads: 4
      type: bigquery
    prod:
      dataset: dbt_prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: sql-training-422508
      threads: 4
      type: bigquery
    stagingenv:
      dataset: dbt_stagingenv
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: sql-training-422508
      threads: 4
      type: bigquery
  target: dev
jaffle_shop_training:
  outputs:
    dev:
      dataset: dbt_ablom
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: sql-training-422508
      threads: 4
      type: bigquery
  target: dev
