default:
  target: bigquery_dev
  outputs:
    bigquery_dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BQ_DATASET', 'dbt_dev') }}"
      threads: 4
      location: US