steps:
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Change to your dbt project directory
        cd jaffle_shop

        # Install Python dependencies
        pip install -r ../requirements.txt

        # Install dbt packages
        dbt deps

        # Run all models now that merge is accepted
        dbt build --target prod --profiles-dir ../

options:
  logging: CLOUD_LOGGING_ONLY
