steps:
- name: 'python:3.12'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cd jaffle_shop
      pip install dbt-core dbt-bigquery
      dbt deps
      dbt build --profiles-dir ../ --target prod

options:
  logging: CLOUD_LOGGING_ONLY

# Optional: You can set a timeout if builds might take long
timeout: '900s'  # 15 minutes