name: Scheduled dbt Run (BigQuery)

on:
  schedule:
    - cron: '0 7 * * *'  # every day at 7 AM UTC
  workflow_dispatch:      # manual trigger

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dbt and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-bigquery

      - name: Run dbt
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        run: |
          dbt deps
          dbt seed
          dbt run
          dbt test
